config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  resources :docs

  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      flash[:notice] = "Documento guardado"
      redirect_to @doc
    else
      flash[:alert] = "Hubo un error al guardar el documento"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      flash[:notice] = "Documento actualizado"
      redirect_to @doc
    else
      flash[:alert] = "Hubo un error al actualizar el documento"
      render 'edit'
    end
  end

  def destroy
    if @doc.destroy
      flash[:notice] = "Documento eliminado"
      redirect_to docs_path
    else
      flash[:alert] = "Hubo un error al eliminar el documento"
      redirect_to docs_path
    end
  end

  private
    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: 'button'

app/views/docs/edit.haml
.wrapper_with_padding
  %h1 Editar documento
  
  = render 'docs/form'
  = link_to "Cancelar", doc_path

app/views/docs/index.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc]) }
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length: 50)
    - else
      %h2 Crear documento
      %p Empieza creando documentos y organizando tu vida
      %button= link_to "Crear documento", new_doc_path

app/views/docs/new.haml
.wrapper_with_padding
  %h1 Nuevo documento
  
  = render 'docs/form'

app/views/docs/show.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @doc.title
    %p= simple_format(@doc.content)
    
    .buttons
      = link_to "Editar documento", edit_doc_path(@doc), class: 'button'
      = link_to "Eliminar", doc_path(@doc), method: :delete, data: { confirm: "¿Estas seguro?" }, class: 'button'

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title FileCabinet
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %header
      .header_inner
        = link_to "FileCabinet", root_path, id: 'logo'

        %nav
          -if user_signed_in?
            = link_to "Crear documento", new_doc_path
            = link_to "Salir", destroy_user_session_path, method: :delete
          -else
            = link_to "Ingresar", new_user_session_path
            
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/welcome/index.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Tu vida laboral. Organizada, siempre.
    %button= link_to "Regístrate", new_user_registration_path

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organízate
        %p Todos tus documentos organizados y seguros en un solo lugar.
        %p
          Ahora podras dejar de preocuparte por tus documentos, deja que nosotros nos
          encarguemos para que puedas tenerlos siempre disponibles en cualquier parte.

#bottom_cta
  .wrapper
    %h2 Adelante
    %br
    %button= link_to "Únete ahora", new_user_registration_path